###
GET http://localhost:5000

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "esmet92@yandex.ru",
    "password": "123123123"
}


### Login a user POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "esmet92@yandex.ru",
    "password": "123123123"
}